server:
  port: 8090

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: perfume
    password: perfume

  web:
    resources:
      static-locations: classpath:/perfumeimgs/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

image:
  add-resource-locations: /perfumeimgs/
  add-resource-handler: /perfumeimgs/**
  # PerfumeService 세팅
  image-dir: /productimgs/
  image-url: http://localhost:8090/productimgs/

# 인코딩할 시크릿키 값
jwt:
  secret: dW5pLXJlYWN0LW5naW54LXNwcmluZy1ib290LWp3dC1vcmFjbGUtZG9ja2VyLWVjMi1yZWFjdC1uZ25peC1zcHJpbmctYm9vdC1qd3Qtb3JhY2xlLWRvY2tlci1lYzIK

# 마이바티스 설정
mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.uni.perfumer
  configuration:
    map-underscore-to-camel-case: true
